services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${PORT}
    ports:
      - "3000:${PORT}"
    volumes:
      - node_modules:/app/node_modules
      - .:/app
    environment:
      - NODE_ENV=development
      - MONGO_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_IP=${MONGO_IP}
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - mongo
  mongo:
    image: mongo:noble
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
volumes:
  mongo-data:
  node_modules: